### ISSUE TITLE
docs: TYPE YOUR QUESTION HERE

### ISSUE THREAD

**Issue by Problemas1** [canonical/ubuntu-server-documentation#100]
*Please describe the question or issue you're facing with "Search - Ubuntu Server documentation".*

---
*Reported from: https://documentation.ubuntu.com/server/search/?q=echo "deb http://ddebs.ubuntu.com $(lsb_release -cs) main restricted universe multiverse deb http://ddebs.ubuntu.com $(lsb_release -cs)-updates main restricted universe multiverse deb http://ddebs.ubuntu.com $(lsb_release -cs)-proposed main restricted universe multiverse" | \ sudo tee -a /etc/apt/sources.list.d/ddebs.list

**Comment by bryceharrington** [comment]
Sorry, I don't understand what the question is.
