### ISSUE TITLE
Formatting: code blocks

### ISSUE THREAD

**Issue by s-makin** [canonical/ubuntu-server-documentation#40]
Many pages have code blocks declared as "console", but the resulting rendered documentation has too much syntax highlighting which can make it harder to parse when reading.

It would be much better if these "console" code blocks were changed to "bash" for consistency with the rest of the docs. If there are any code blocks that have no declared language, it would be good to add one (bash, text for output, yaml, etc).

**Comment by panlinux** [comment]
Following this, I filed https://github.com/canonical/ubuntu-server-documentation/issues/102 for us to have consistency regarding the shell prompt in commands.
