### ISSUE TITLE
docs: WireGuard site-to-site, overlapping allowed IP addresses

### ISSUE THREAD

**Issue by gigi96** [canonical/ubuntu-server-documentation#47]
When you say:

"There will be no NAT applied to traffic going over the WireGuard network. Therefore, the networks of both sites must be different and not overlap"

I think it is wrong regarding the scenario "site-to-site". You can have hosts of the two private networks with IP addresses belonging to the same private network

---
*Reported from: https://documentation.ubuntu.com/server/how-to/wireguard-vpn/site-to-site/*

**Comment by panlinux** [comment]
> I think it is wrong regarding the scenario "site-to-site". You can have hosts of the two private networks with IP addresses belonging to the same private network

I suppose you can, but that's for another guide then. Here we are trying to implement exactly the diagram that is being shown, allowing for users to pick their own network blocks of course, in which case this serves as a reminder that in this setup, we expect the networks to not overlap.
