### ISSUE TITLE
docs: Link on page broken

### ISSUE THREAD

**Issue by Nebuer01** [canonical/ubuntu-server-documentation#49]
*Please describe the question or issue you're facing with "WireGuard VPN peer-to-site - Ubuntu Server documentation".*

The links at the bottom of the page with the text `"another system in the home network"` and `"on the router"` do not go to an active webpage. The link destination is `https://discourse.ubuntu.comwireguard-on-an-internal-system.md/` and `https://discourse.ubuntu.comwireguard-vpn-peer-to-site-on-router.md/` respectively, however these do not exist.

It seems that it should link to `https://documentation.ubuntu.com/server/how-to/wireguard-vpn/on-an-internal-system/` and `https://documentation.ubuntu.com/server/how-to/wireguard-vpn/peer-to-site-on-router/`

The page which has this problem is `https://documentation.ubuntu.com/server/how-to/wireguard-vpn/peer-to-site/`

---
*Reported from: https://documentation.ubuntu.com/server/how-to/wireguard-vpn/peer-to-site/*

**Comment by s-makin** [comment]
Hi @Nebuer01 and thanks for taking the time to report this - I'll get a PR in today to fix them

**Comment by s-makin** [comment]
This has now been fixed. Thanks again for reporting the issue!
