### ISSUE TITLE
Question: OpenLDAP backend (legacy)

### ISSUE THREAD

**Issue by cscowx** [canonical/ubuntu-server-documentation#58]
*Please describe the question or issue you're facing with "OpenLDAP backend (legacy) - Ubuntu Server documentation".*

My current operating system environment is:
ubuntu 22.04
samba 4.15.13

Article mentioned in/usr/share/doc/samba/examples/LDAP directory of samba ldif file, I didn't find it under the local path
Also, I want to know how to configure samba4 to integrate with openldap now?

---
*Reported from: https://documentation.ubuntu.com/server/how-to/samba/openldap-backend-legacy/*

**Comment by panlinux** [comment]
> Article mentioned in/usr/share/doc/samba/examples/LDAP directory of samba ldif file, I didn't find it under the local path

It's in the `samba` package, which was installed in the guide just a few lines up:
```
$ dpkg -L samba|grep samba\\.ldif
/usr/share/doc/samba/examples/LDAP/samba.ldif
/usr/share/samba/setup/provision_dns_add_samba.ldif

$ dpkg -l samba
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version                   Architecture Description
+++-==============-=========================-============-===============================================
ii  samba          2:4.15.13+dfsg-0ubuntu1.6 amd64        SMB/CIFS file, print, and login server for Unix
```

> Also, I want to know how to configure samba4 to integrate with openldap now?

The current way is to just deploy samba as an Active Directory Domain Controller, which will install its own LDAP server (not openldap). The guide for that is https://documentation.ubuntu.com/server/how-to/samba/provision-samba-ad-controller/

I'm not sure how flexible that is with regards to custom schemas and other attributes you might be using, so maybe the legacy way, with OpenLDAP, is still your best option.
