### ISSUE TITLE
doc: Dead Link on Configure Apache2 Settings Page

### ISSUE THREAD

**Issue by quapaw-language** [canonical/ubuntu-server-documentation#62]
The "Extend Apache Capabilities with Modules" link toward the end of the article is supposed to redirect to a .md file titled "How to Use Apache2 Modules" but the associated URL is improper: https://discourse.ubuntu.comhow-to-use-apache2-modules.md/

Additionally, even when adding a forward slash between ".com" and "how," I am redirected to a 404 page.
---
Document: how-to/web-services/configure-apache2-settings.md

**Comment by s-makin** [comment]
Good catch, thanks for reporting it! I thought I'd found all those. I'll put in a PR to fix that today.

**Comment by s-makin** [comment]
Fixed by #63

**Comment by quapaw-language** [comment]
Appreciate y'all, thanks for what you do!
