### ISSUE TITLE
doc: "+search" missing in dig command

### ISSUE THREAD

**Issue by Eulenbit** [canonical/ubuntu-server-documentation#70]
DESCRIBE THE ISSUE
The line
<code>dig @localhost +short -t A $(hostname)</code>
is probably missing an
<code>+search</code>
or alternatively a "<code>-f</code>" as <code>hostname</code>'s argument.
---
Document: how-to/samba/provision-samba-ad-controller.md

**Comment by panlinux** [comment]
Hello,

you are correct, thanks for raising this.
