### ISSUE TITLE
doc: broken links and references

### ISSUE THREAD

**Issue by mduregon** [canonical/ubuntu-server-documentation#73]
attached an amended document including correct references and links 

[how-to-netboot-the-server-installer-on-amd64.md.txt.new.txt](https://github.com/user-attachments/files/17639287/how-to-netboot-the-server-installer-on-amd64.md.txt.new.txt)
[how-to-netboot-the-server-installer-on-amd64.md.txt.orig.txt](https://github.com/user-attachments/files/17639288/how-to-netboot-the-server-installer-on-amd64.md.txt.orig.txt)

---
Document: how-to/installation/how-to-netboot-the-server-installer-on-amd64.md

**Comment by s-makin** [comment]
Hi @mduregon and thanks for taking the time to detail these proposed changes! I've created a pull request containing your suggestions

**Comment by cpaelzer** [comment]
That was merged three weeks ago, but forgot to mark the commits as closing this issue :-/
Doing so now, and thanks again @mduregon for reporting it!
