### ISSUE TITLE
docs: TYPE YOUR QUESTION HERE

### ISSUE THREAD

**Issue by shaapan** [canonical/ubuntu-server-documentation#74]
*Please describe the question or issue you're facing with "OpenSSH server - Ubuntu Server documentation".*

---
*Reported from: https://documentation.ubuntu.com/server/how-to/security/openssh-server/?_ga=2.43334949.1694707443.1730808742-86180010.1730808742*

**Comment by s-makin** [comment]
Hi @shaapan and thanks for opening an issue - could you add some information about the problem you found so that we can look into it? Many thanks!

**Comment by panlinux** [comment]
Closing as there is no content in this report.
