### ISSUE TITLE
docs: TYPE YOUR QUESTION HERE

### ISSUE THREAD

**Issue by AlexB1974** [canonical/ubuntu-server-documentation#78]
*Please describe the question or issue you're facing with "Install and configure LDAP - Ubuntu Server documentation".*

---
*Reported from: https://documentation.ubuntu.com/server/how-to/openldap/install-openldap/?_ga=2.259387722.1376012459.1731321254-2009774675.1728884382

**Comment by panlinux** [comment]
Closing as there is no content in this report.
