### ISSUE TITLE
Typo in networking: serve-ntp-with-chrony title

### ISSUE THREAD

**Issue by guitarpicva** [canonical/ubuntu-server-documentation#96]
*Please describe the question or issue you're facing with "How to server the Network Time Protocol with Chrony - Ubuntu Server documentation".*

typo: "server" should be "serve"

---
*Reported from: https://documentation.ubuntu.com/server/how-to/networking/serve-ntp-with-chrony/

**Comment by cpaelzer** [comment]
PR #98 was merged but forgot to close this issue.
Doing so now - and many thanks @guitarpicva for reporting it!
